services:
- type: web
  name: alexandria
  env: docker
  healthCheckPath: /healthz
  envVars:
  - key: HASURA_GRAPHQL_DATABASE_URL
    fromDatabase:
      name: alexandria
      property: connectionString
  - key: HASURA_GRAPHQL_ENABLE_CONSOLE
    value: true
  - key: PORT
    value: 10000
  - key: HASURA_GRAPHQL_ADMIN_SECRET
    generateValue: true
databases:
- name: alexandria
